### ISSUE TITLE
created fo4dds ba2s are invalid

### ISSUE THREAD

**Issue by Guekka** [Ryan-rsm-McKenzie/bsa#8] opened 2021-11-25 06:27 UTC
I am currently investigating, but haven't found anything yet

**Reproducing**:
- Create a fo4dds archive
- Open in archive2
- Delete a single file
- Try to save the archive
- Lots of errors will appear about "unsupported file type"

**Recap of what I found so far**:
- `BitsPerPixel` should be always `8`.
- `Flags` should be 0 or 1 if the texture is a cubemap
- It looks like archive2 does not produce the same archive header as rsm-bsa. I linked an example below. bsarch is correct, so studying its code may help. The first difference is the string table offset

**Comment by Guekka** [comment] 2021-11-25 09:20
I'm not sure it is enough, but on my small sample, the fix was to change `BitsPerPixel`. Dividing it by 4 fixed the issue

**Comment by Guekka** [comment] 2021-11-25 09:22
I've also noticed bsarch does not have `Flags` and `BitsPerPixel`. Instead, it has `cubemaps`:

https://github.com/TES5Edit/TES5Edit/blob/dev/Tools/BSArchive/wbBSArchive.pas#L278

**Comment by Guekka** [comment] 2021-11-25 11:20
Dividing `BitsPerPixel` per 4 is not a good solution. But I am still pretty confident the bug comes from this part

**Comment by Guekka** [comment] 2021-11-25 15:24
The problem might be more important than expected. rsm-bsa does not produce the same hash as archive2 with the linked file

bsarch gets it right, so looking at the code might be helpful

[test.zip](https://github.com/Ryan-rsm-McKenzie/bsa/files/7603947/test.zip)

**Comment by Ryan-rsm-McKenzie** [comment] 2021-11-25 23:52
What are the permissions on this file?

**Comment by Ryan-rsm-McKenzie** [comment] 2021-11-26 00:12
I see what the issue is, beth does a bunch of stupid stuff to calculate chunk size and bits per pixel

**Comment by Ryan-rsm-McKenzie** [comment] 2021-11-26 07:37
Fixed by 84c18fc96c022c584194cb7a43b5f250b0cc5f0a, but it still needs tests to guard against regressions, such as textures with cubemaps. The texture provided here is also a good sample, since it found a bug in how textures were chunked, but it depends on the licensing.

**Comment by Guekka** [comment] 2021-11-26 08:20
The licensing does not allow it, but the author is active. I've asked for permission

**Comment by Guekka** [comment] 2021-11-26 08:40
Can confirm the fix appears to be working. The archive produced by rsm-bsa are still different, but I suppose it's only the file order

**Comment by Guekka** [comment] 2022-01-26 11:43
Already 2 months? Time flies
So, I've found another mod to reproduce the bug, and it has open permissions. https://www.nexusmods.com/skyrim/mods/95466?
I tried with the whole mod, but `mushroom01_e` is marked as "XBOXDDS"

**Comment by Ryan-rsm-McKenzie** [comment] 2022-02-10 06:50
These files don't manage to add test coverage for the newly discovered chunking strategy for dds files, but they did manage to uncover a new bug. I believe cubemaps are excluded from chunking, which is what the flag in the archive file header is for.

**Comment by Ryan-rsm-McKenzie** [comment] 2022-02-10 06:54
Added more coverage and another fix in e96e4abdd6fc4eea07b333c5ae7fbe587d46ee31

**Comment by Guekka** [comment] 2022-02-17 17:46
So, do you know the consequences of this bug? I didn't get any report, so I assume it doesn't cause CTD?

**Comment by Guekka** [comment] 2022-02-17 18:21
[texture.zip](https://github.com/Ryan-rsm-McKenzie/bsa/files/8091169/texture.zip)

So, here's the texture that originally found the issue. I manually blacked it out. Pretty sure we can't get permission issue after that

**Comment by Ryan-rsm-McKenzie** [comment] 2022-02-18 03:41
Added coverage for chunking in 63c01e2c04252d3224b5bf1cbbe6dfcdf615acd2

**Comment by Ryan-rsm-McKenzie** [comment] 2022-02-18 03:49
I don't know if there's _actually_ an issue with chunking archives incorrectly, but it's best to conform to whatever `Archive2.exe` produces.

**Closed** 2022-02-18 03:50 UTC
